# Write your MySQL query statement below
SELECT E.EMPLOYEE_ID FROM
EMPLOYEES E LEFT JOIN SALARIES S
ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
WHERE SALARY IS NULL

UNION

SELECT S.EMPLOYEE_ID FROM
EMPLOYEES E RIGHT JOIN SALARIES S
ON E.EMPLOYEE_ID = S.EMPLOYEE_ID
WHERE NAME IS NULL
ORDER BY EMPLOYEE_ID;